import Navbar from "./Navbar/Navbar";
import Head from "next/head";
import { useUser } from "../context/authContext";
import { Box, Flex, useColorModeValue } from "@chakra-ui/react";
import Footer from "./Footer/Footer";
import BackgroundWaves from "./BackgroundWaves";

const Layout = ({ children }) => {
  const { user } = useUser();

  const waves = useColorModeValue("waves", "waves2");

  return (
    <>
      <Head>
        <title>Tyler Tierney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ width: "100vw" }}>
        <Flex className={waves} minH="93vh" minW="100vw"></Flex>
        <Navbar />
        <Box maxW="100vw" mt="7vh" minH="100vh" paddingX={["3", "8", "0", "0"]}>
          {children}
        </Box>
      </main>

      <Footer />
    </>
  );
};

export default Layout;
