import Navbar from "./Navbar/Navbar";
import Head from "next/head";
import { useUser } from "../context/authContext";
import { Box, Flex } from "@chakra-ui/react";
import Footer from "./Footer/Footer";

const Layout = ({ children }) => {
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ width: "100vw" }}>
        <Navbar />
        <Box
          maxW="100vw"
          mt="7vh"
          minH="100vh"
          // h="93vh"
          // maxH="93vh"
          paddingX={["3", "8", "0", "0"]}
        >
          {children}
        </Box>
      </main>

      <Footer />
    </>
  );
};

export default Layout;
