import Navbar from "./Navbar/Navbar";
import Head from "next/head";
import { useUser } from "../context/authContext";
import { Box } from "@chakra-ui/react";

const Layout = ({ children }) => {
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Box
          maxW="100vw"
          mt="7vh"
          h="93vh"
          maxH="93vh"
          // paddingY={["8", "10", "14"]}
          paddingX={["3", "8", "0"]}
        >
          {children}
        </Box>
      </main>
    </>
  );
};

export default Layout;
